name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/redshift-transformation

  REDSHIFT_HOST: "testing.cx4py8yq28xb.us-east-1.redshift.amazonaws.com"
  REDSHIFT_PORT: "5439"
  REDSHIFT_DATABASE: "gh_actions_transformation_tests"
  REDSHIFT_SCHEMA: "gh_actions_transformation_tests"
  REDSHIFT_USER: "gh_actions_transformation_tests"
  REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}

  KBC_DEVELOPERPORTAL_VENDOR: "keboola"
  KBC_DEVELOPERPORTAL_APP: "keboola.redshift-transformation"
  KBC_DEVELOPERPORTAL_USERNAME: "keboola+redshift_transformation_gh_actions"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Build image
        run: docker build -t $APP_IMAGE .
      - name: Run tests
        run: |
          docker run \
           -e REDSHIFT_HOST \
           -e REDSHIFT_PORT \
           -e REDSHIFT_DATABASE \
           -e REDSHIFT_SCHEMA \
           -e REDSHIFT_USER \
           -e REDSHIFT_PASSWORD \
          $APP_IMAGE \
          composer ci
      - name: Push image to ECR
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
          docker tag $APP_IMAGE:latest $REPOSITORY:test
          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
          docker push $REPOSITORY:test
          docker pull quay.io/keboola/syrup-cli:latest
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: ./deploy.sh
